### ISSUE TITLE
Add office telemetry powershell script

### ISSUE THREAD

**Issue by Obegg** [gravesoft/gravesoft.dev#3]
I guess it's not off-topic here

https://github.com/abbodi1406/WHD/pull/8

**Comment by WindowsAddict** [comment]
@Obegg Abbodi already added in his repo, it should be enough for you. We will decide about adding this later or not, Closing it here for now.

**Comment by Obegg** [comment]
> Abbodi already added in his repo

Yes, because I sent a PR.

But what I'm suggesting is adding the following lines to the website so that users (other than me, you and the author) will know about it at least:
```powershell
Invoke-Expression (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/abbodi1406/WHD/master/scripts/OC2R_DisableTelemetry.ps1')
```
```powershell
Invoke-Expression (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/abbodi1406/WHD/master/scripts/OC2R_RevertTelemetry.ps1')
```

The reason I'm suggesting it is because there's already a good powershell command right here:
https://massgrave.dev/#method-1---powershell
Which activates MAS.

Then why not include the telemetry scripts aswell?

**Comment by WindowsAddict** [comment]
@Obegg I'm not a fan of anti-telemetry scripts, some of it will break some features in O365, besides, it's just one of the thousands of things that can also be added to the site. We will look into adding this into the future, no promises.
