### ISSUE TITLE
Office 2016 installer doesn't work on Windows 7

### ISSUE THREAD

**Issue by ChaseKnowlden** [gravesoft/gravesoft.dev#5]
The procedure entry point SetProcessMitigationPolicy could not be located in the dynamic link library KERNEL32.dll.

Office 2016 Supports Windows 7.

**Comment by WindowsAddict** [comment]
Use 2016 offline installer as mentioned in the notes section.
Online version is not supported because its set to use a version which is unsupported on windows 7.

**Comment by ChaseKnowlden** [comment]
Thanks!
