### ISSUE TITLE
Update Custom Installation Guide (Office LTSC 2024)

### ISSUE THREAD

**Issue by alexchexes** [gravesoft/gravesoft.dev#6]
Hi!

The guide for custom configuration (https://gravesoft.dev/office_c2r_custom) currently mentions `Office LTSC Professional Plus 2021 - Volume License`, although Microsoft released Office LTSC **2024** in September.

Could you confirm if it’s safe to select `Office LTSC Professional Plus 2024 - Volume License` in the configuration (and later activate it with MAS tools), or if there are any caveats? If it's ok, could you update the guide to reflect this version update?

**Comment by WindowsAddict** [comment]
https://github.com/gravesoft/gravesoft.dev/commit/2a047746466c79e3f5ecdb165951d7b9e35b2beb

Done.
